//
// Created by oiluz on 9/4/2017.
//

#ifndef GUACAMOLE_GUACDEFINES_H
#define GUACAMOLE_GUACDEFINES_H

#define ADD_USER_COMMAND "ADD"
#define REMOVE_USER_COMMAND "REMOVE"
#define STOP_PROCESS_COMMAND "STOP"
#define COMMAND_DELIMITER "/"

#define SOCKET_BUFFER_SIZE 8192
#define SHM_SELECT_MS 15000

#define GLOBAL_SHARED_MEMORY_NAME "SharedMemory"
#define USER_SHARED_MEMORY_PREFIX "UserSharedMemory"

#ifdef WIN32
#define LIB_EXTENSION "dll"
#else
#define LIB_EXTENSION "so"
#endif
#define PROTOCOL_BUFFER_MAX_LEN 32
#define LIBRARY_FOLDER_BUFFER_MAX_LEN 512
#define LOGGER_FOLDER_BUFFER_MAX_LEN 512
#define FPS_BUFFER_MAX_LEN 4

#define GUAC_SHARED_MEMORY_GLOBAL_QUEUE_SIZE 2
#define GUAC_SHARED_MEMORY_GLOBAL_PACKET_SIZE 256

#define GUAC_SHARED_MEMORY_USER_QUEUE_SIZE 1024
#define GUAC_SHARED_MEMORY_USER_PACKET_SIZE 1024

#endif //GUACAMOLE_GUACDEFINES_H